config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome_page'
  get 'home/index'
  get 'home/welcome_page'
  get 'home/pages/:file' => 'home#pages'
  get 'home/companion_to_becl'
  get 'home/download_becl_books'
  get 'home/popup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def welcome_page
  end

  def companion_to_becl
  end

  def sample_page
  end

  def popup
  end

  def pages
    path = 'home/pages/'+params[:file]
    render path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
  def panel_link path: nil, text: nil, icon: nil
    render 'application/phone/panel_link', path: path, text: text, icon_name: icon
  end
end

app/views/application/phone/_left_panel.html.haml
/ Left panel with reveal effect
.panel.panel-left.panel-reveal
  .list-block
    %ul
      = panel_link text: "All Topics", icon: 'edit', path: home_index_path

app/views/application/phone/_panel_link.html.haml
%li
  = link_to path, class: 'close-panel item-link ripple-color-red' do
    .item-content{style:"color:#2679b5;font-weight:bolder;"}
      .item-inner
        .item-title
          - if icon_name
            = image_tag(icon_name, size: "35x25", alt: "book image", style:"margin-bottom: -5px;")
            &nbsp;
          = text

app/views/home/christ.html.haml
.page.page-current
  .page-content
    .block-title CHRIST
    .list
      %ul
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title His person
          .accordion-item-content
            .block
              %h3 God:
              %h4
                John 1:1
                %sup 4-5
              %h4
                John 1:2
                %sup 2
              %h4
                John 8:24
                %sup 1
              %h4
                Heb. 1:8
                %sup 1
              %h4
                Rom. 9:5
                %sup 1
              %h4
                1 John 5:20
                %sup 7-8
              %h3 Man:
              %h4
                Matt. 26:64
                %sup 1
              %h4
                Matt. 4:4
                %sup 2
              %h4
                Rom. 1:3
                %sup 4-5
              %h4
                Rom. 5:15
                %sup 1
              %h4
                Heb. 2:6
                %sup 1
              %h4
                Heb. 9
                %sup 1
              %h4
                1 Tim. 2:5
                %sup 3
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title His natures
          .accordion-item-content
            .block
              %h3 Both human and divine:
              %h4
                Rom. 1:3
                %sup 1, 4
              %h4
                Rom. 4
                %sup 1-2,4
              %h4
                Matt. 22:45
                %sup 1
              %h4
                1 John 1:7
                %sup 4
              %h4
                John 1:51
                %sup 3
              %h4
                Heb. 3:3
                %sup 2
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title His process and work
          .accordion-item-content
            .block
              %h3 Incarnation:
              %h4
                Luke 1:35
                %sup 2
                ;
              %h4
                Matt. 1:18
                %sup 1
                ;
              %h4
                John 1:14
                %sup 1-2
                (para. 1-2)
                ;
              %h4
                Col. 2:9
                %sup 3
                ;
              %h4
                Rom. 1:3
                %sup 4-5
                ;
                8:3
                %sup 3
                ;
              %h4
                Phil. 2:7
                %sup 3
              %h3 Human living:
              %h4
                John 1:14
                %sup 3
                ;
                7:1
                %sup 1
                , 6
                %sup 1
                , 10
                %sup 1
                , 15
                %sup 1
                , 41
                %sup 1
                ;
              %h4
                Matt. 11:29
                %sup 2-3
                ;
              %h4
                Mark 10:45
                %sup 1, 3
                ;
              %h4
                Heb. 2:9
                %sup 1
                , 10
                %sup 5
                ;
              %h4
                Eph. 4:21
                %sup 1
                ;
              %h4
                1 Pet. 2:21
                %sup 2
              %h3 Death:
              %h4
                Mark 14:36
                %sup 1
                ;
              %h4
                1 Pet. 2:24
                %sup 1
                ;
                3:18
                %sup 1
                ;
              %h4
                2 Cor. 5:21
                %sup 1-4
                ;
              %h4
                Heb. 2:14
                %sup 1
                ;
              %h4
                John 12:31
                %sup 1
                , 24
                %sup 1
                , 32
                %sup 1
                ;
              %h4
                Mark 10:1
                %sup 1
                ;
                John 19:30
                %sup 2
                , 34
                %sup 1
                ;
              %h4
                Heb. 10:20
                %sup 2
              %h3 Resurrection:
              %h4
                Mark 16:6
                %sup 1
                ;
              %h4
                Matt. 28:1
                %sup 2
                ;
              %h4
                Rom. 4:25
                %sup 1
                ;
              %h4
                Acts 2:24
                %sup 1-2
                ;
                13:33
                %sup 1
                ;
              %h4
                1 Cor. 15:45
                %sup 1
                ;
              %h4
                1 Pet. 1:3
                %sup 7
              %h4
                John 12:23
                %sup 1
                , 24
                %sup 2
                ;
                20:1
                %sup 1-2
              %h4
                John 20:17
                %sup 2-3
                ;
              %h4
                Rom. 8:29
                %sup 4
                ;
              %h4
                1 Cor. 15:3
                %sup 1
                , 12
                %sup 1
                , 17
                %sup 1-2
                , 54
                %sup 3
                , 57
                %sup 1
              %h3 Ascension:
              %h4
                (Secret) John 20:17
                %sup 1
                ;
                (Public) Mark 16:19
                %sup 1
                ;
              %h4
                John 6:62
                %sup 1
                ;
              %h4
                Luke 24:51
                %sup 1
                ;
              %h4
                Heb. 7:26
                %sup 1
                ;
              %h4
                Phil. 2:9
                %sup 1-3
                , 11
                %sup 2
                ;
              %h4
                Acts 2:36
                %sup 1
                ;
                1:11
                %sup 2-5
                ;
              %h4
                Eph. 4:8
                %sup 1-3
              %h3 Consummating in the Spirit:
              %h4
                John 7:39
                %sup 1
                ;
              %h4
                1 Cor. 15:45
                %sup 1
                ;
              %h4
                2 Cor. 3:17
                %sup 2-3
                ;
              %h4
                Rom. 8:10
                %sup 1
              %h3 Second coming:
              %h4
                Matt. 24:3
                %sup 3
                , 27
                %sup 1
                , 43
                %sup 2
                ;
              %h4
                Acts 1:11
                %sup 3-5
                ;
              %h4
                Rev. 10:1
                %sup 2
                ;
                14:14
                %sup 1-2

        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title His being all-inclusive
          .accordion-item-content
            .block
              %h4
                Matt. 1:1
                %sup 1
                , 17
                %sup 4
                ;
              %h4
                Heb. 1:2
                %sup 4
                , 3
                %sup 4
                , 5
                %sup 1
                ;
                12:2
                %sup 5
                ;
              %h4
                1 Cor. 1:9
                %sup 2
                ;
              %h4
                Col. 1:12
                %sup 1-2
                ;
                2:6
                %sup 2
                , 16
                %sup 4
                , 17
                %sup 3

app/views/home/christian_experience.html.haml
.page.page-current
  .page-content
    .block-title  CHRISTIAN EXPERIENCE
    .list
      %ul
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Called by God
          .accordion-item-content
            .block
              %h4
                2 Tim. 1:9
                %sup 1-2
                ;
              %h4
                Rom. 1:6
                %sup 1
                ;
              %h4
                Acts 7:2
                %sup 2
                ;
              %h4
                2 Pet. 1:3
                %sup 8
                ;
              %h4
                1 Cor. 1:2
                %sup 6,8
                , 9
                %sup 2
                ;
              %h4
                Eph. 1:18
                %sup 4
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Repenting
          .accordion-item-content
            .block
              %h4
                Matt. 3:2
                %sup 1-2
                , 3
                %sup 2
                ;
              %h4
                Mark 1:15
                %sup 2
                ;
              %h4
                1 Thes. 1:9
                %sup 2
                ;
              %h4
                Acts 5:31
                %sup 4
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Believing into Christ
          .accordion-item-content
            .block
              %h4
                Mark 1:15
                %sup 3
                ;
              %h4
                Rom. 3:22
                %sup 1
                ;
              %h4
                John 1:12
                %sup 1
                ;
                3:16
                %sup 2
                ;
              %h4
                Col. 2:6
                %sup 1
                ;
              %h4
                Rom. 10:9
                %sup 2
                , 10
                %sup 1
                ;
                1:5
                %sup 3-4
                ;
              %h4
                Gal. 3:26
                %sup 2
                ;
              %h4
                Phil. 1:29
                %sup 1
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Calling on the name of the Lord
          .accordion-item-content
            .block
              %h4
                Acts 2:21
                %sup 1-3
                ;
                9:14
                %sup 1
                ;
              %h4
                Phil. 2:11
                %sup 1-3
                ;
              %h4
                Rom. 10:8
                %sup 1
                , 9
                %sup 1
                , 10
                %sup 1
                , 12
                %sup 1
                , 13
                %sup 1-2
                , 14
                %sup 1
                ;
              %h4
                1 Cor. 1:2
                %sup 8
                ;
                12:3
                %sup 3
                ;
              %h4
                2 Tim. 2:22
                %sup 3
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Baptism
          .accordion-item-content
            .block
              %h4
                Mark 16:16
                %sup 1-2
                ;
              %h4
                Matt. 3:6
                %sup 1
                ;
              %h4
                Mark 1:8
                %sup 1
                ;
              %h4
                Acts 8:36
                %sup 1
                ;
              %h4
                1 Cor. 10:2
                %sup 1-3
                ;
              %h4
                Eph. 4:5
                %sup 2
                ;
              %h4
                Matt. 28:19
                %sup 3-5
                ;
              %h4
                Rom. 6:3
                %sup 1
                \- 5
                %sup 3
              %h4
                Gal. 3:27
                %sup 1
                ;
              %h4
                1 Cor. 12:13
                %sup 1-5
                ;
              %h4
                Acts 2:38
                %sup 3
                ;
              %h4
                1 Pet. 3:20
                %sup 3
                , 21
                %sup 1, 3-4;
              %h4
                Acts 16:33
                %sup 1
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Living and walking by the Spirit
          .accordion-item-content
            .block
              %h4
                Col. 2:6
                %sup 1-2
                ;
              %h4
                1 Cor. 6:17
                %sup 1-2
                ;
              %h4
                Rom. 8:4
                %sup 1-2
                , 5
                %sup 2-3
                , 6
                %sup 2-3
                , 14
                %sup 1
                , 15
                %sup 1
                , 16
                %sup 1-3
                ;
              %h4
                Gal. 5:16
                %sup 1-2
                , 25
                %sup 1-2
                ;
              %h4
                Eph. 3:16
                %sup 5-6
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Prayer
          .accordion-item-content
            .block
              %h4
                Eph. 6:18
                %sup 1-6
                ;
              %h4
                John 15:7
                %sup 2
                , 16
                %sup 5
                ;
              %h4
                1 John 5:14
                %sup 3
                ;
              %h4
                Heb. 4:16
                %sup 1
                ;
              %h4
                Phil. 4:6
                %sup 1-4
                , 7
                %sup 1
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Confession of sins
          .accordion-item-content
            .block
              %h4
                1 John 1:9
                %sup 1-2
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Enjoying grace
          .accordion-item-content
            .block
              %h4
                John 1:14
                %sup 6
                , 17
                %sup 1
                ;
              %h4
                Rom. 1:7
                %sup 2
                ;
                5:2
                %sup 1-3
                , 17
                %sup 1
                ;
              %h4
                1 Cor. 15:10
                %sup 1-2
                ;
              %h4
                Gal. 2:21
                %sup 1
                ;
              %h4
                Eph. 2:8
                %sup 2
                Rom. 12:6
                %sup 1
                ;
              %h4
                Eph. 4:7
                %sup 2
                ;
              %h4
                Heb. 4:16
                %sup 1-2
                ;
              %h4
                1 Pet. 4:10
                %sup 2
                ;
                5:10
                %sup 2, 4
                ;
              %h4
                Rev. 22:21
                %sup 1
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Walking in love
          .accordion-item-content
            .block
              %h4
                1 Cor. 2:9
                %sup 3
                ;
                8:1
                %sup 4
                ;
                13:4
                %sup 1
                , 8
                %sup 1
                , 13
                %sup 1
                ;
              %h4
                Rom. 13:8
                %sup 1
                ;
              %h4
                Gal. 5:6
                %sup 3
                ;
              %h4
                2 Tim. 3:2
                %sup 2
                ;
              %h4
                Eph. 1:4
                %sup 7
                ;
                3:17
                %sup 4
                ;
                5:2
                %sup 1
                , 25
                %sup 1
                ;
                6:23
                %sup 2-3
                , 24
                %sup 2-3
                ;
              %h4
                2 Pet. 1:7
                %sup 1-2
                ;
              %h4
                John 15:17
                %sup 1
                ;
                21:15
                %sup 4
                ;
              %h4
                Rev. 2:4
                %sup 1-2
                ;
              %h4
                1 John 2:5
                %sup 2,4
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Serving the Lord
          .accordion-item-content
            .block
              %h4
                Luke 10:42
                %sup 1
                ;
                16:1
                %sup 1
                ;
              %h4
                Matt. 20:26
                %sup 1
                ;
                25:14
                %sup 3
                ;
              %h4
                Rom. 1:1
                %sup 2-4
                , 9
                %sup 1-2
                ;
                12:1
                %sup 5,7
                , 11
                %sup 1
                ;
              %h4
                1 Pet. 4:11
                %sup 2-3

app/views/home/companion_to_becl.html.haml
= render partial: 'shared/header', locals: { back: 'true', title: 'Companion to BECL', icon: 'logo-mark.svg'}
.page-content
  .block
    Use the links below to view/download each PDF file.
  .block-title.topic Pdf links
  .list
    %ul
      %li
        .item-content.list-item
          %a.close-panel.item-link.item-inner.item-title.link.external{href:"/companion_pdf/2018_BECL_Vol_1_companion_FINAL.pdf" , class: "close-panel item-link", :target => "_blank"}
            %i.fa.fa-file-pdf-o.red
            &nbsp;
            Companion to BECL, vol. 1
            %i.fa.fa-external-link
      %li
        .item-content.list-item
          %a.close-panel.item-link.item-inner.item-title.link.external{href:"/companion_pdf/2018_BECL_Vol_2_companion_FINAL.pdf" , class: "close-panel item-link", :target => "_blank"}
            %i.fa.fa-file-pdf-o.red
            &nbsp;
            Companion to BECL, vol. 2
            %i.fa.fa-external-link
      %li
        .item-content.list-item
          %a.close-panel.item-link.item-inner.item-title.link.external{href:"/companion_pdf/2018_BECL_Vol_3_companion_FINAL.pdf" , class: "close-panel item-link", :target => "_blank"}
            %i.fa.fa-file-pdf-o.red
            &nbsp;
            Companion to BECL, vol. 3
            %i.fa.fa-external-link

app/views/home/divine_truth_reality.html.haml
.page.page-current
  .page-content
    .block-title  DIVINE TRUTH —REALITY
    .list
      %ul
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title All the realities of the divine economy
          .accordion-item-content
            .block
              %h4
                1 John 1:6
                %sup 6
              %h4
                1 John 1:8
                %sup 3
                ;
              %h4
                1 Tim. 2:4
                %sup 2
                ;
                3:15
                %sup 5
                ;
              %h4
                2 Tim. 2:15
                %sup 2
                , 25
                %sup 1
                ;
              %h4
                Titus 1:1
                %sup 3
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The divine reality embodied, revealed, and expressed in Christ
          .accordion-item-content
            .block
              %h4
                John 18:37
                %sup 1
                ;
                1:14
                %sup 6
                ;
                14:6
                %sup 2
                ;
              %h4
                Eph.4:21
                %sup 1
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The reality which is the Spirit
          .accordion-item-content
            .block
              %h4
                John 14:17
                %sup 1
                ,26
                %sup 1
                ;
                15:26
                %sup 1
                ;
                16:13
                %sup 1
                ;
              %h4
                1 John 5:6
                %sup 4-5
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The substance of God’s word
          .accordion-item-content
            .block
              %h4
                John 17:17
                %sup 2-3
                ;
              %h4
                Col. 1:5
                %sup 3
                ;
              %h4
                2 Cor. 4:2
                %sup 2
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The truth which we must hold to, obey, and walk in
          .accordion-item-content
            .block
              %h4
                Eph. 4:15
                %sup 1
                ;
              %h4
                1 Pet. 1:22
                %sup 2-3
                ;
              %h4
                3 John 3
                %sup 2-3
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The reality in our living
          .accordion-item-content
            .block
              %h4
                John 4:24
                %sup 5
                ;
              %h4
                Eph. 6:14
                %sup 3
                ;
              %h4
                1 John 1:6
                %sup 6
                pt. 7
                ;
              %h4
                2 John 1
                %sup 3
                , 13
                %sup 1

app/views/home/download_becl_books.html.haml
= render partial: 'shared/header', locals: { back: 'true', title: 'Download BECL Books', icon: 'logo-mark.svg'}
.page-content
  .block
    Use the links below to view/download each volume of
    %span.italic Basic Elements of Christian Life.
  .block-title.topic DOWNLOAD FREE BOOKS
  .list
    %ul
      %li
        .item-content.list-item
          %a.close-panel.item-link.item-inner.item-title.link{href:"/home/popup?book=1" , class: "close-panel item-link"}
            %i.fa.fa-file-pdf-o.red
            &nbsp;
            %span.italic Basic Elements of the Christian Life,
            vol. 1
            %i.fa.fa-external-link
      %li
        .item-content.list-item
          %a.close-panel.item-link.item-inner.item-title.link{href:"/home/popup?book=2" , class: "close-panel item-link"}
            %i.fa.fa-file-pdf-o.red
            &nbsp;
            %span.italic Basic Elements of the Christian Life,
            vol. 2
            %i.fa.fa-external-link
      %li
        .item-content.list-item
          %a.close-panel.item-link.item-inner.item-title.link{href:"/home/popup?book=3" , class: "close-panel item-link"}
            %i.fa.fa-file-pdf-o.red
            &nbsp;
            %span.italic Basic Elements of the Christian Life,
            vol. 3
            %i.fa.fa-external-link

app/views/home/eternal_life.html.haml
.page.page-current
  .page-content
    .block-title  ETERNAL LIFE
    .list
      %ul
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The divine, uncreated life of God
          .accordion-item-content
            .block
              %h4
                John 3:15
                %sup 1
                ;
                17:3
                %sup 1
                ;
              %h4
                Rom. 6:23
                %sup 3
                ;
              %h4
                Eph. 4:18
                %sup 2
                ;
              %h4
                1 Tim. 1:16
                %sup 2
                ;
                6:12
                %sup 2-3
                ;
              %h4
                2 Tim. 1:10
                %sup 3-4
                ;
              %h4
                1 John 1:2
                %sup 1-6
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title Different from the physical or soulish life
          .accordion-item-content
            .block
              %h4
                Rom. 5:17
                %sup 4
                ;
              %h4
                John 10:11
                %sup 1
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The life of the tree of life
          .accordion-item-content
            .block
              %h4
                John 1:4
                %sup 1
                ;
              %h4
                Rev. 2:7
                %sup 6
                ;
                22:2
                %sup 1
                , 14
                %sup 4
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title A living person, Christ Himself
          .accordion-item-content
            .block
              %h4
                John 14:6
                %sup 1
                ;
              %h4
                1 John 5:11
                %sup 1
                , 12
                %sup 1
                ;
                2:25
                %sup 1, 3
                ;
              %h4
                Col. 3:4
                %sup 1-2
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title he life which regenerates the believers to be God’s children
          .accordion-item-content
            .block
              %h4
                John 1:12
                %sup 2
                ;
                3:3
                %sup 3
                , 6
                %sup 2
                , 16
                %sup 1
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The life which we should lay hold on and hope in
          .accordion-item-content
            .block
              %h4
                1 Tim. 6:12
                %sup 2
                ;
              %h4
                Titus 1:2
                %sup 1
                , 6
                %sup 2
                ;
              %h4
                1 Pet. 1:3
                %sup 6
        %li.accordion-item
          %a.item-content.item-link{:href => "#"}
            .item-inner
              .item-title The way we can experience life and grow in life
          .accordion-item-content
            .block
              %h4
                1 Pet. 2:2
                %sup 4
                ;
                John 6:57
                %sup 1
                , 63
                %sup 1-3
                ;
                Rom. 8:2
                %sup 2-3
                , 4
                %sup 2
                , 6
                %sup 1-2
                ;
                1 John 1:7
                %sup 2-3

app/views/home/index.html.haml
= render partial: 'shared/header', locals: { back: 'true', title: 'Recovery Version Bible Study Topics', icon: 'logo-mark.svg' }
.page-content
  .block-title.topic List Of Topics
  .list.accordion-list
    %ul
      = panel_link text: "THE WORD OF GOD", path: '/home/pages/the_word_of_god'
      = panel_link text: "GOD", path: '/home/pages/god'
      = panel_link text: "THE ECONOMY OF GOD", path: '/home/pages/the_economy_of_god'
      = panel_link text: "CHRIST", path: '/home/pages/christ'
      = panel_link text: "THE SPIRIT", path: '/home/pages/the_spirit'
      = panel_link text: "ETERNAL LIFE", path: '/home/pages/eternal_life'
      = panel_link text: "DIVINE TRUTH—REALITY", path: '/home/pages/divine_truth_reality'
      = panel_link text: "MAN", path: '/home/pages/man'
      = panel_link text: "THE GOSPEL", path: '/home/pages/the_gospel'
      = panel_link text: "SALVATION", path: '/home/pages/salvation'
      = panel_link text: "CHRISTIAN EXPERIENCE", path: '/home/pages/christian_experience'
      = panel_link text: "THE BELIEVERS", path: '/home/pages/the_believers'
      = panel_link text: "THE CHURCH—THE BODY OF CHRIST", path: '/home/pages/the_church_the_body_of_christ'
      = panel_link text: "THE KINGDOM", path: '/home/pages/the_kingdom'
      = panel_link text: "THE NEW JERUSALEM", path: '/home/pages/the_new_jerusalem'

app/views/home/sample_page.html.haml
= render partial: 'shared/header', locals: { back: 'true', title: 'Companion to Basic Elements of the Christian Life', icon: 'logo-mark.svg'}
.page-content
  %a.link.external{href:"/companion_pdf/2018_BECL_Vol_1_companion_FINAL.pdf" , style:"color:gray !important;", :target => "_blank"} hgjhgjg
  / %object{:data => "/companion_pdf/2018_BECL_Vol_1_companion_FINAL.pdf", :height => "100%", :type => "application/pdf", :width => "100%"}